apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-wit2024
spec:
  replicas: 2  # Number of running frontend instances/  previous 1
  selector:
    matchLabels:
      app: my-frontend-wit2024
  template:
    metadata:
      labels:
        app: my-frontend-wit2024
    spec:
      containers:
      - name: my-frontend-wit2024
        image: rhodgar14/my-frontend-wit2024:latest
        ports:
        - containerPort: 8081