apiVersion: v1
kind: Service
metadata:
  name: my-frontend-wit2024
spec:
  selector:
    app: my-frontend-wit2024
  ports:
    - protocol: TCP
      port: 8081       # Service port exposed to the cluster
      targetPort: 80   # Port on the NGINX container
  type: ClusterIP