apiVersion: v1
kind: Service
metadata:
  name: my-backend-wit2024
spec:
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 80  # Service port exposed to Ingress
      targetPort: 32000  # Matches the port your Spring Boot app listens on
  type: ClusterIP
