apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-wit2024
spec:
  replicas: 2  # Number of running backend instances previous 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      imagePullSecrets:
        - name: my-dockerhub-secret
      containers:
        - name: springboot
          image: rhodgar14/my-backend-wit2024:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "test"
            - name: SPRING_PORT
              value: "32000"  # Ensure the app inside listens on 32000 if changed
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://my-db-wit2024:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # Name of the secret
                  key: SPRING_DATASOURCE_USERNAME  # Key for the username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # Name of the secret
                  key: SPRING_DATASOURCE_PASSWORD  # Key for the password
          ports:
            - containerPort: 32000  # Change this to 32000 to match the SPRING_PORT environment variable