apiVersion: v1
kind: Service
metadata:
  name: my-db-wit2024
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432  # The port your PostgreSQL container listens on
  clusterIP: None       # Make this a headless to not occupy public ip

