apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db-wit2024
spec:
  serviceName: postgres  # Service used to discover the database
  replicas: 1  # Keep it at 1 unless you set up replication
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: db-credentials
      containers:
        - name: postgres
          image: rhodgar14/my-db-wit2024:latest
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata  # Set PGDATA to a subdirectory
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # Using Kubernetes secret for sensitive data
                  key: SPRING_DATASOURCE_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage  # Match the name with volumeClaimTemplates
              mountPath: /var/lib/postgresql/data  # Mount to this path
  volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-storage  # Ensure the name matches
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi  # Persistent storage size
