apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-wit2024
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: db-credentials
      containers:
        - name: postgres
          image: rhodgar14/my-db-wit2024:latest
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "wit2024"
          ports:
            - containerPort: 5432
